spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:C:/temp/db
    hikari:
      username: "test"
      password: "1234"
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
